services:
  proton:
    image: ghcr.io/timeplus-io/proton:latest
  hn_datagen:
    build:
      context: .  
    image: timeplus/hackernews_bytewax:latest
    environment:
      - PROTON_HOST=proton
    depends_on:
      - proton